### ISSUE TITLE
set inheritAttrs only?

### ISSUE THREAD

**Issue by joo1es** [chenxch/vite-plugin-vue-setup-extend-plus#2]
"name" field is required now, but sometimes i wanna set inheritAttrs only. This avoids some unnecessary "name" set when setting inheritAttrs.

**Comment by chenxch** [comment]
Received, I will notify you when processing is complete.

**Comment by chenxch** [comment]
A new version has been released, you can upgrade to version 0.1.0. Or use [unplugin-vue-setup-extend-plus](https://www.npmjs.com/package/unplugin-vue-setup-extend-plus).

**Comment by chenxch** [comment]
@joo1es 
A new version has been released, you can upgrade to version 0.1.0. Or use [unplugin-vue-setup-extend-plus](https://www.npmjs.com/package/unplugin-vue-setup-extend-plus).

**Comment by joo1es** [comment]
Good Job!

**Comment by chenxch** [comment]
> Good Job!

Thanks for the advice, have a good day.
