### ISSUE TITLE
配置插件后项目启动失败

### ISSUE THREAD

**Issue by liuyichens** [chenxch/vite-plugin-vue-setup-extend-plus#5]
vite 3.1.0 插件配置后项目启动失败
![配置](https://user-images.githubusercontent.com/43558322/196828682-838bef04-6daf-43f1-ad09-0252a75f83a3.jpg)
![启动](https://user-images.githubusercontent.com/43558322/196828693-512a23d7-55c4-4ded-94e5-acbf93171017.jpg)

**Comment by chenxch** [comment]
是vueSetupExtend哦

**Comment by liuyichens** [comment]
还是一样的错误提示 
vueSetupExtend is not a function

**Comment by chenxch** [comment]
你打印一下vueSetupExtend 看下是什么

**Comment by chenxch** [comment]
hello~ 是否有新进展，如果还是不行的你看下方便提供一个简易的demo么

**Comment by liuyichens** [comment]
![tessss](https://user-images.githubusercontent.com/43558322/197118623-028f58b6-a0e0-4c2e-a924-1cfff13a1857.png)
这个是打印结果，就是刚刚用vite创建了vue3项目，第一个安装的就是这个插件

**Comment by chenxch** [comment]
那新创建的这个还是异常？ 方便的话吧demo提交上一份我看下

**Comment by liuyichens** [comment]
ok,大佬回复速度快啊

**Comment by liuyichens** [comment]
https://gitee.com/liuyichen1/vite-demo

**Comment by chenxch** [comment]
收到

**Comment by chenxch** [comment]
问题定位到了，是因为项目package.json中开启了`"type": "module",`模式，插件包目前是走cjs，你可以先注释这个，晚点我支持一下es

**Comment by chenxch** [comment]
兼容需要更换编译方式，建议是用增强版[unplugin-vue-setup-extend-plus](https://www.npmjs.com/package/unplugin-vue-setup-extend-plus)。

**Comment by liuyichens** [comment]
好的，谢谢

**Comment by chenxch** [comment]
如果还有问题的话在那个项目中找我哈，这个我先关闭了哦

**Comment by liuyichens** [comment]
好的，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chenxch/vite-plugin-vue-setup-extend-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月24日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chenxch/vite-plugin-vue-setup-extend-plus] 配置插件后项目启动失败 (Issue #5)





 
如果还有问题的话在那个项目中找我哈，这个我先关闭了哦

**Comment by 1071125093** [comment]
nb
